name: Protected envs and stages

on:
  pull_request:
    branches: [master]
  push:
    branches:
      - master


jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout github repository
        uses: actions/checkout@v4

      - name: Build or simulate building
        run: sleep 5

      - name: Finish building
        run: echo "Build completed successfully"
  
  deploy-dev:
    environment : DEV
    runs-on: ubuntu-latest
    steps:
      - name: deploying
        run: sleep 3
      - name: Print
        run: echo "Deployed to dev"
  
  deploy-acc:
    environment : ACC
    runs-on: ubuntu-latest
    steps:
      - name: deploying
        run: sleep 3
      - name: Print
        run: echo "Deployed to acc"
  
  deploy-pro:
    environment : PRO
    runs-on: ubuntu-latest
    steps:
      - name: deploying
        run: sleep 3
      - name: Print
        run: echo "Deployed to pro"