name: Greetings

on: push
#  schedule:
#    - cron: "*/5 * * * *"

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: hallokes 
        uses: ./.github/actions/hallokes-bokkes
        with:
          user-name: "Frédèrick"