name: Greetings

on:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: hallokes 
        run: ./.github/actions/hallokes-bokkes
        with:
          user-name: "Frédèrick"