name: Protected envs and stages Matrix

on:
  pull_request:
    branches: [master]
  push:
    branches:
      - master


jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout github repository
        uses: actions/checkout@v4

      - name: Build or simulate building
        run: sleep 5

      - name: Finish building
        run: echo "Build completed successfully"
  
  deploy-env:
    runs-on: ubuntu-latest
    needs: [build-and-push]
    strategy:
      fail-fast: true
      max-parallel: 1
      matrix:
        environment: [ 'DEV', 'ACC', 'PRO' ]
    environment: ${{ matrix.environment }}
    steps:
      - name: deploying
        run: sleep 3
      - name: Print
        run: echo "Deployed to ${{ matrix.environment }}"
  
  